language: node_js
node_js:
  - "8"
  - "10"
  - "12"
env:
  - SUITE=unit
  - SUITE=lint
matrix:
  exclude:
    - node_js: "4"
      env: SUITE=lint
    - node_js: "5"
      env: SUITE=lint
    - node_js: "6"
      env: SUITE=lint
    - node_js: "7"
      env: SUITE=lint
    - node_js: "8"
      env: SUITE=lint
    - node_js: "9"
      env: SUITE=lint
install:
  - npm install
script:
  - npm run $SUITE
